// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_yoiRFvXyPfpjYkpwXXXoUDBI1v0moOE',
    appId: '1:656268601844:android:0250938cde779c20edf1a1',
    messagingSenderId: '656268601844',
    projectId: 'hossamclinic-5193a',
    storageBucket: 'hossamclinic-5193a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnxIE8HK3DKz0e1tFjPAPvDGkwBkRzMDQ',
    appId: '1:656268601844:web:86988e09adb2a5dbedf1a1',
    messagingSenderId: '656268601844',
    projectId: 'hossamclinic-5193a',
    authDomain: 'hossamclinic-5193a.firebaseapp.com',
    storageBucket: 'hossamclinic-5193a.firebasestorage.app',
    measurementId: 'G-YNG466H50V',
  );
  static const FirebaseOptions web = windows;
}
